dropdown mvc/Models/Data/ApplicationContect.cs
using dropdown_mvc.Models;
using dropdownmvc.Models.cascande;
using Microsoft.EntityFrameworkCore;
namespace dropdownmvc.Models.Data
{
    public class ApplicationContect : DbContext
    {
        public ApplicationContect(DbContextOptions<ApplicationContect> options) :base(options)
        {

        }
        public DbSet<Country> countries { get; set; }
        public DbSet<State> states { get; set; }
        public DbSet<City> citys { get; set; }

        
    }
}

dropdown mvc/Models/ErrorViewModel.cs
namespace dropdown_mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

dropdown mvc/Models/cascande/City.cs
using MessagePack;
using System.ComponentModel.DataAnnotations.Schema;

namespace dropdownmvc.Models.cascande
{
    public class City
    {
        
        public int Id { get; set; }
        public string? Name { get; set; }
       
        public State State { get; set; }
    }
}

dropdown mvc/Models/cascande/Country.cs
using System.ComponentModel.DataAnnotations;

namespace dropdownmvc.Models.cascande
{
    public class Country
    {
        [Key]
        public int Id { get; set; }
        public string? Name { get; set; }
    }
}

dropdown mvc/Models/cascande/State.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace dropdownmvc.Models.cascande
{
    public class State
    {
        [Key]
        public int Id { get; set; }
        public string? Name { get; set; }
       
        public Country Country { get; set; }
    }
}

dropdown mvc/Controllers/CascadeController.cs
using dropdownmvc.Models.Data;
using Microsoft.AspNetCore.Mvc;

namespace dropdownmvc.Controllers
{
    public class CascadeController : Controller
    {
        private readonly ApplicationContect context;
         
        public CascadeController(ApplicationContect context) 
        {
            this.context = context;
        }
        public JsonResult Country()
        {
            var cnt=context.countries.ToList();
            return new JsonResult(cnt);

        }
        public JsonResult State(int? id)
        {
            var st=context.states.Where(e =>e.Country.Id == id).ToList();
            return new JsonResult(st);
        }
        public JsonResult City(int? id)
        {
            var ct=context.citys.Where(e => e.State.Id == id).ToList();
            return new JsonResult(ct);
        }

        public ActionResult CascadeDropdown()
        {
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

dropdown mvc/Controllers/HomeController.cs
using dropdown_mvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace dropdownmvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

dropdown mvc/Views/Cascade/CascadeDropdown.cshtml
@{
    ViewData["Title"] = "CascadeDropdown";
}



<h1>CascadeDropdown</h1>

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <form method="post">
                <div class="form-group">
                    <label><b>Country</b></label><br />
                    <select class="form-cotrol" id="Country" name="Country">
                        <option>----Select country----</option>
                    </select>
                </div>
                <br />
                <div class="form-group">
                    <label><b>State</b></label><br />
                    <select class="form-cotrol" id="State" name="State">
                        <option>----Select State----</option>
                    </select>
                </div>
                <br />

                <div class="form-group">
                    <label><b>City</b></label><br />
                    <select class="form-cotrol" id="City" name="City">
                        <option>----Select City----</option>
                    </select>
                </div>
                <br />
                <div class="form-group">
                    <button type="button" class="btn btn-sm btn-primary float-right " onclick="DropDown();">Save</button>

                </div>
            </form>
            <br />
            <br />
            <div>
            <table  id="tbl" class="table table-bordered-9 text-lg-center " border="1">
            <thead >
                <tr>
                 <th>Country Name</th>
                 <th>State Name</th>
                 <th>City price</th>
                </tr>
            <thead>
            <tbody>


            </tbody>
            </table>


        </div>
        </div>
    </div>
</div>

<script>
        function DropDown() {
            let CountryName = document.getElementById("Country");
            let stateName = document.getElementById("State");
            let CityName = document.getElementById("City");


            var countryText = CountryName.options[CountryName.selectedIndex].text;
            var stateText = stateName.options[stateName.selectedIndex].text;
            var cityText = CityName.options[CityName.selectedIndex].text;


            let table = document.getElementById("tbl");
            let newRow = table.insertRow(table.rows.length);

            newRow.insertCell(0).innerHTML = countryText;
            newRow.insertCell(1).innerHTML = stateText;
            newRow.insertCell(2).innerHTML = cityText;

        }
    </script>

    
<a href="~/lib/jquery/dist/jquery.min.map"></a>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/cascade.js"></script>

dropdown mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

dropdown mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dropdownmvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/dropdown_mvc.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">dropdownmvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cascade" asp-action="CascadeDropdown">CascadeDropdown</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - dropdown_mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>